stages:
  - build
  - push
  - deploy

build:
  stage: build
  # tags:
  #   - docker-build
  script:
    - echo "Building Docker Image..."
    - docker --version
    - docker build -t $CI_REGISTRY_IMAGE .

push:
  stage: push
  # tags:
  #   - docker-build
  script:
    - echo "Pushing Docker image to GitLab Container Registry..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
    - docker push "$CI_REGISTRY_IMAGE"

deploy:
  stage: deploy
  # before_script:
  #   # Setup SSH deploy keys
  #   - eval $(ssh-agent -s)
  #   - ssh-add <(echo "$RUNNER_SSH_KEY")
  #   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh tls@192.168.1.200 "cd ./flaskapp && docker login -u '$CI_REGISTRY_USER' -p '$CI_JOB_TOKEN' '$CI_REGISTRY' && 
      docker compose pull flask-be && docker compose up -d flask-be && exit"
